spring:
  application:
    name: order-service

  rabbitmq:
    host: 192.168.72.136
    port: 5672
    username: admin
    password: admi
    
#server:
 # port: 8004

eureka:
  client:
    service-url:
      defaultZone: http://eureka1:2001/eureka,http://eureka2:2002/eureka

feign:
  hystrix:
    enabled: true
    
management:
  endpoints:
    web:
      exposure:
        include: hystrix.stream
        
---
spring:
  profiles: order1
  
server:
  port: 8201
  
---
spring:
  profiles: order2
  
server:
  port: 8202
  